from __future__ import annotations

from typing import Protocol
from uuid import UUID

from src.contexts.clients.domain.client import Client


class ClientRepository(Protocol):
    async def add(self, client: Client) -> None: ...
    async def get(self, client_id: UUID) -> Client: ...
    async def list_for_owner(self, owner_id: UUID) -> list[Client]: ...
    async def update(self, client: Client) -> None: ...
    async def delete(self, client_id: UUID) -> None: ...
