from __future__ import annotations

from typing import Protocol
from uuid import UUID

from src.contexts.vehicles.domain.vehicle import Vehicle


class VehicleRepository(Protocol):
    async def add(self, vehicle: Vehicle) -> None: ...
    async def get(self, vehicle_id: UUID) -> Vehicle: ...
    async def list_for_owner(self, owner_id: UUID) -> list[Vehicle]: ...
    async def update(self, vehicle: Vehicle) -> None: ...
    async def delete(self, vehicle_id: UUID) -> None: ...
