from __future__ import annotations

from typing import Protocol
from uuid import UUID

from src.contexts.loans.domain.entities.loan import Loan


class LoanRepository(Protocol):
    async def add(self, loan: Loan) -> None: ...
    async def get(self, loan_id: UUID) -> Loan: ...
    async def list_by_client(self, client_id: UUID) -> list[Loan]: ...
    async def list_all(self) -> list[Loan]: ...
    async def update(self, loan: Loan) -> None: ...
    async def delete(self, loan_id: UUID) -> None: ...
