"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-07 16:38:42.025361

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('vehicle_price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('initial_payment_pct', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('balloon_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('term_periods', sa.Integer(), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('rate_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grace_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('additional_charges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_client_id'), 'loans', ['client_id'], unique=False)
    op.create_table('operations_log',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_log_user_id'), 'operations_log', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clients',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_owner_id'), 'clients', ['owner_id'], unique=False)
    op.create_table('payment_schedule_entries',
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('grace_type', sa.String(length=1), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('interest', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('payment', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('amortization', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('final_balance', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('charges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'period', name='uq_schedule_loan_period')
    )
    op.create_index(op.f('ix_payment_schedule_entries_loan_id'), 'payment_schedule_entries', ['loan_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('list_price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_owner_id'), 'vehicles', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_owner_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_payment_schedule_entries_loan_id'), table_name='payment_schedule_entries')
    op.drop_table('payment_schedule_entries')
    op.drop_index(op.f('ix_clients_owner_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_operations_log_user_id'), table_name='operations_log')
    op.drop_table('operations_log')
    op.drop_index(op.f('ix_loans_client_id'), table_name='loans')
    op.drop_table('loans')
    # ### end Alembic commands ###
